[tools]
direnv = '2.32.2'
task = '3.23.0'
pre-commit = '2.19.0'
python = '3.11.1'
shfmt = '3.6.0'
shellcheck = '0.8.0'

[plugins]
direnv = 'https://github.com/asdf-community/asdf-direnv'
task = 'https://github.com/particledecay/asdf-task'
shellcheck = 'https://github.com/luizm/asdf-shellcheck'
python = 'https://github.com/rtx-plugins/rtx-python'
shfmt = 'https://github.com/luizm/asdf-shfmt'
pre-commit = 'https://github.com/jonathanmorley/asdf-pre-commit'

[settings] # project-local settings
verbose = true
